---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-stable
  namespace: vops-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: microservice
      version: stable
  template:
    metadata:
      labels:
        app: microservice
        version: stable
    spec:
      containers:
        - name: app
          image: damiano000/vops-microservice:stable
          ports:
            - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-canary
  namespace: vops-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice
      version: canary
  template:
    metadata:
      labels:
        app: microservice
        version: canary
    spec:
      containers:
        - name: app
          image: damiano000/vops-microservice:canary
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: microservice
  namespace: vops-dev
spec:
  selector:
    app: microservice
  ports:
    - port: 80
      targetPort: 80
