apiVersion: v1
kind: Service
metadata:
  name: vops-microservice
  namespace: vops-dev
spec:
  type: NodePort
  selector:
    app: vops-microservice
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30010