apiVersion: apps/v1
kind: Deployment
metadata:
  name: vops-microservice
  namespace: vops-prod
  labels:
    app: vops-microservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vops-microservice
  template:
    metadata:
      labels:
        app: vops-microservice
    spec:
      containers:
        - name: vops-microservice
          image: damiano000/vops-microservice:v17
          ports:
            - containerPort: 5000
          env:
            - name: ENV
              value: "prod"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 2
            periodSeconds: 5
